-- =============================================================
-- 묻다 — 오늘의 질문 + 지인에게 물어보기 (2026-07-08, 사장님 기획)
--
-- 흐름:
--   1) 내가 오늘의 질문에 답한다 (self)
--   2) "OO님은 뭐라고 답할까?" 추측을 적는다 (guess)
--   3) 같은 질문을 지인에게 링크로 보낸다 (비회원 응답 가능)
--   4) 지인이 답 제출 시 공개/비공개 선택 —
--      공개(shared)면 나에게 보이고, 비공개(private)면 절대 안 보임
--   5) 질문 상세에서 내 답·내 추측·지인의 실제 답을 나란히 본다
--
-- 개인정보 원칙:
--   · 응답자 답 내용은 테이블 직접 SELECT 불가(정책 없음) —
--     모든 접근은 RPC 경유, private 답은 inviter RPC에서도 내용 미반환.
--   · 응답자는 계정 불필요(코드 토큰만). 이름은 선택 입력.
--
-- 멱등. 적용: Supabase SQL Editor 1회 실행.
-- =============================================================

begin;

-- ── 1) 질문 사전 ─────────────────────────────────────────────
create table if not exists public.mutda_daily_questions (
  id            int generated by default as identity primary key,
  text          text not null,
  display_order int not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

alter table public.mutda_daily_questions enable row level security;

drop policy if exists mutda_daily_questions_read on public.mutda_daily_questions;
create policy mutda_daily_questions_read on public.mutda_daily_questions
  for select to anon, authenticated using (is_active);

insert into public.mutda_daily_questions (text, display_order)
select v.text, v.ord
from (values
  ('시간을 되돌린다면, 언제로 돌아가고 싶나요?', 1),
  ('죽기 전에 꼭 만나고 싶은 사람은 누구인가요?', 2)
) as v(text, ord)
where not exists (
  select 1 from public.mutda_daily_questions d where d.text = v.text
);

-- ── 2) 내 답 · 내 추측 ───────────────────────────────────────
create table if not exists public.mutda_question_answers (
  id              uuid primary key default gen_random_uuid(),
  question_id     int not null references public.mutda_daily_questions(id) on delete cascade,
  user_id         uuid not null references auth.users(id) on delete cascade,
  kind            text not null check (kind in ('self','guess')),
  target_name     text,          -- guess일 때: 누구에 대한 추측인지
  target_relation text,          -- 엄마/아빠/배우자/자녀/형제자매/친구/기타
  content         text not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- self 답은 질문당 1개 (덮어쓰기), guess는 대상별 여러 개 허용
create unique index if not exists mutda_question_answers_self_uniq
  on public.mutda_question_answers (user_id, question_id)
  where kind = 'self';

create index if not exists mutda_question_answers_user_idx
  on public.mutda_question_answers (user_id, question_id);

alter table public.mutda_question_answers enable row level security;

drop policy if exists mutda_question_answers_owner on public.mutda_question_answers;
create policy mutda_question_answers_owner on public.mutda_question_answers
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ── 3) 지인 초대 + 응답 (RPC 전용 — 직접 SELECT 정책 없음) ──
create table if not exists public.mutda_question_invites (
  id                    uuid primary key default gen_random_uuid(),
  code                  text not null unique,
  question_id           int not null references public.mutda_daily_questions(id) on delete cascade,
  inviter_id            uuid not null references auth.users(id) on delete cascade,
  inviter_name          text,             -- 응답 페이지에 "OO님이 물어요" 표기용 스냅샷
  target_name           text,             -- 보낸 사람이 지정한 상대 이름(선택)
  target_relation       text,
  created_at            timestamptz not null default now(),
  answered_at           timestamptz,
  respondent_name       text,
  respondent_visibility text check (respondent_visibility in ('shared','private')),
  respondent_content    text
);

create index if not exists mutda_question_invites_inviter_idx
  on public.mutda_question_invites (inviter_id, question_id);

alter table public.mutda_question_invites enable row level security;
-- 정책 없음 = anon/authenticated 직접 접근 불가. 아래 RPC(security definer)로만.

-- 초대 생성 (로그인 필요)
create or replace function public.mutda_question_invite_create(
  p_question_id int, p_target_name text default null, p_target_relation text default null
) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_code text;
  v_name text;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select coalesce(mp.name, split_part(u.email, '@', 1)) into v_name
    from auth.users u left join public.mutda_profiles mp on mp.user_id = u.id
   where u.id = auth.uid();
  v_code := upper(substr(md5(gen_random_uuid()::text), 1, 8));
  insert into public.mutda_question_invites
    (code, question_id, inviter_id, inviter_name, target_name, target_relation)
  values (v_code, p_question_id, auth.uid(), v_name,
          nullif(trim(coalesce(p_target_name,'')), ''), p_target_relation);
  return v_code;
end $$;

-- 응답 페이지 미리보기 (비회원 가능 — 질문·보낸 사람만, 답 내용 미노출)
create or replace function public.mutda_question_invite_preview(p_code text)
returns table (question_text text, inviter_name text, target_name text, answered boolean)
language sql security definer set search_path = public stable as $$
  select q.text, i.inviter_name, i.target_name, (i.answered_at is not null)
    from public.mutda_question_invites i
    join public.mutda_daily_questions q on q.id = i.question_id
   where i.code = upper(trim(p_code));
$$;

-- 응답 제출 (비회원 가능, 1회만)
create or replace function public.mutda_question_invite_submit(
  p_code text, p_content text, p_visibility text, p_respondent_name text default null
) returns boolean
language plpgsql security definer set search_path = public as $$
declare v_updated int;
begin
  if coalesce(trim(p_content), '') = '' then raise exception 'EMPTY_CONTENT'; end if;
  if p_visibility not in ('shared','private') then raise exception 'BAD_VISIBILITY'; end if;
  update public.mutda_question_invites
     set answered_at = now(),
         respondent_content = left(trim(p_content), 2000),
         respondent_visibility = p_visibility,
         respondent_name = nullif(left(trim(coalesce(p_respondent_name,'')), 40), '')
   where code = upper(trim(p_code)) and answered_at is null;
  get diagnostics v_updated = row_count;
  if v_updated = 0 then raise exception 'ALREADY_ANSWERED_OR_NOT_FOUND'; end if;
  return true;
end $$;

-- 내가 보낸 초대 목록 (private 답은 내용 null — 존재만 알림)
create or replace function public.mutda_question_my_invites(p_question_id int default null)
returns table (
  code text, question_id int, target_name text, target_relation text,
  created_at timestamptz, answered_at timestamptz,
  respondent_name text, visibility text, content text
)
language sql security definer set search_path = public stable as $$
  select i.code, i.question_id, i.target_name, i.target_relation,
         i.created_at, i.answered_at, i.respondent_name,
         i.respondent_visibility,
         case when i.respondent_visibility = 'shared' then i.respondent_content else null end
    from public.mutda_question_invites i
   where i.inviter_id = auth.uid()
     and (p_question_id is null or i.question_id = p_question_id)
   order by i.created_at desc;
$$;

revoke all on function public.mutda_question_invite_create(int, text, text) from public;
revoke all on function public.mutda_question_invite_preview(text) from public;
revoke all on function public.mutda_question_invite_submit(text, text, text, text) from public;
revoke all on function public.mutda_question_my_invites(int) from public;
grant execute on function public.mutda_question_invite_create(int, text, text) to authenticated;
grant execute on function public.mutda_question_invite_preview(text) to anon, authenticated;
grant execute on function public.mutda_question_invite_submit(text, text, text, text) to anon, authenticated;
grant execute on function public.mutda_question_my_invites(int) to authenticated;

commit;
